name: amitbet/dicom build
on: [push, pull_request]
jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code 
      uses: actions/checkout@v1

    - name: Get dependencies
      run: | 
            export GOPATH=$HOME/go
            export GOBIN=$GOPATH/bin
            export REPO_PATH=$GOPATH/src/github.com/amitbet/dicom
            mkdir -p $GOBIN 
            export PATH=$PATH:/home/runner/go/bin
            mkdir -p $REPO_PATH
            mv $(pwd)/* $REPO_PATH 
            cd $REPO_PATH 
            go mod download


    - name: Build
      run: |
            export GOPATH=$HOME/go
            export GOBIN=$GOPATH/bin
            export REPO_PATH=$GOPATH/src/github.com/amitbet/dicom
            export PATH=$PATH:/home/runner/go/bin
            cd $REPO_PATH
            make
   
    - name: Test
      run: |
            export GOPATH=$HOME/go
            export GOBIN=$GOPATH/bin 
            export REPO_PATH=$GOPATH/src/github.com/amitbet/dicom
            export PATH=$PATH:/home/runner/go/bin
            cd $REPO_PATH
            make test

